import board.GameBoard;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        GameBoard gameBoard = new GameBoard(10, 10);
        gameBoard.draw();
    }
}
