import java.util.Scanner;

import game.GameEngine;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public static void main(String[] args) {
    GameEngine gameEngine = new GameEngine();
    gameEngine.registerPlayers();
    gameEngine.startGame();
  }
}
